language: cpp
sudo: required
branches:
  only:
    - master
            
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      compiler: gcc
      env:
        - WITH_TEST=yes
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_install:
        - eval "${MATRIX_EVAL}"
      install: 
        - cmake --version
        - g++ -v
      script: 
        - cmake . -DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=ON -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-linux
        - make
        
    - os: windows
      install: 
        - cmake --version
      env:
        - WITH_TEST=yes
      script: 
        - cmake.exe -G "Visual Studio 15 2017" -DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=ON -DCMAKE_TOOLCHAIN_FILE=C:\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows -S .
        - cmake.exe --build . --config Debug
        - cmake.exe --build . --config Release
        
before_script:
    - |
      if [ "$TRAVIS_OS_NAME" = linux ]; then
        (
          cd $HOME &&
          git clone --depth 1 -b master https://github.com/microsoft/vcpkg.git vcpkg &&
          cd vcpkg &&
          ./bootstrap-vcpkg.sh &&
          ./vcpkg install curl[non-http]:x64-linux &&
          ./vcpkg install cpprestsdk:x64-linux
          if [ "$WITH_TEST" = "yes" ]; then
            ./vcpkg install gtest:x64-linux
          fi
        )
      fi
    - |
      if [ "$TRAVIS_OS_NAME" = windows ]; then
        (
          cd C: &&
          git clone --depth 1 -b master https://github.com/microsoft/vcpkg.git vcpkg &&
          cd vcpkg &&
          .\\bootstrap-vcpkg.bat &&
          .\\vcpkg.exe install curl[non-http]:x86-windows &&
          .\\vcpkg.exe install cpprestsdk:x86-windows
          if [ "$WITH_TEST" = "yes" ]; then
            .\\vcpkg.exe install gtest:x86-windows
          fi
        )
      fi

notifications:
  email: false
